[package]
name = "advent-of-rust-2022"
version = "0.1.0"
authors = ["Hugo Tunius <h@tunius.se>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
lazy_static = "1"
